Import sort with Prettier and Pre Commit with Husky
steven-tey/dub pull request #62
Opened 2022-10-05 12:43 UTC by max-programming

Continuation of #55 and also added Pre Commit Git Hooks that will format the code once it gets committed

2022-10-05 23:24 UTC, steven-tey requested changes
Thanks a lot for your work on this! However, I'm not sure how I feel about all the spaces that it's creating in the code base (refer https://github.com/trivago/prettier-plugin-sort-imports#output)

Is it possible to remove all spaces?

Also, is it possible to make this script run on every CMD+S, HMR-style?

2022-10-05 23:24 UTC, steven-tey commented on .husky/pre-commit
> +#!/usr/bin/env sh
I'm probably missing something here but why is this file needed? Can we remove it?

2022-10-06 06:01 UTC, max-programming commented
@steven-tey by spaces, do you mean the separation between those imports?

2022-10-07 16:51 UTC, max-programming commented
On it 🔥

2022-10-09 06:19 UTC, max-programming commented
@steven-tey Done with changes

2022-10-09 07:15 UTC, steven-tey commented
Sorry for being a bit annoying with this but is it possible to remove all changes except for the prettier file, and vscode ones? I wanna run Prettier locally to make sure everything looks good before merging 😅

2022-10-09 07:58 UTC, max-programming commented
Sure thing

2022-10-09 08:03 UTC, max-programming commented
Looks like it's quite hard to go through more than 90 files and change them.

2022-10-11 16:08 UTC, max-programming commented
@steven-tey Conflicts will increase if we don't deal with this now 😄

2022-10-11 16:10 UTC, steven-tey commented
@max-programming could you create a new PR and commit only the `.prettierrc.json` and the `.vscode` config file? Don't run prettier locally please (and don't put it in `package.json` yet), I'll double check that and run it before merging. Thank you!

2022-10-11 16:35 UTC, max-programming commented
@steven-tey So don't you want the `format:write` script and husky in the new PR?

2022-10-11 18:20 UTC, closed without merging

2022-10-11 18:21 UTC, max-programming commented
I hope #76 works. Let me know if you need more than that